# Hypridle: bloqueio por inatividade e suspensão.
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Bloqueia após 5 minutos de inatividade.
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# Desliga a tela após 5 minutos e meio.
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspende após 30 minutos.
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
